(ns kifshare.test.configs
  (:use [clojure.test])
  (:require [clojure.string :as string]
            [kifshare.config :as config]))

(deftest test-default-configs
  (require 'kifshare.config :reload)
  (config/local-init "dev-resources/mostly-defaults.properties")
  (testing "default configuration settings"
    (is (= (config/robots-txt-path) "robots.txt"))
    (is (= (config/client-cache-scope) "public"))
    (is (= (config/client-cache-max-age) "604800"))
    (is (= (config/resources-root) "/resources"))
    (is (= (config/js-dir) "js"))
    (is (= (config/img-dir) "img"))
    (is (= (config/css-dir) "css"))
    (is (= (config/flash-dir) "flash"))
    (is (= (config/de-url) "https://de.example.org/de"))
    (is (= (config/irods-url) "https://wiki.example.org/display/start/Using+icommands"))
    (is (= (config/logo-path) "resources/img/logo.png"))
    (is (= (config/favicon-path) "resources/img/logo.ico"))
    (is (= (config/de-import-flags) "{{url}}/d/{{ticket-id}}/{{filename}}"))
    (is (= (config/footer-text) "This is the footer text."))
    (is (= (config/curl-flags) "curl -o '{{filename}}' '{{url}}/d/{{ticket-id}}/{{filename}}'"))
    (is (= (config/wget-flags) "wget '{{url}}/d/{{ticket-id}}/{{filename}}'"))
    (is (= (config/iget-flags) "iget -t {{ticket-id}} '{{abspath}}'"))
    (is (= (config/username) "public"))
    (is (= (config/irods-host) "irods"))
    (is (= (config/irods-port) "1247"))
    (is (= (config/irods-password) "notprod"))
    (is (= (config/irods-home) "/iplant/home"))
    (is (= (config/irods-zone) "iplant"))
    (is (= (config/irods-default-resource) ""))
    (is (= (config/css-files)
           (string/split config/default-css-files #"\s*,\s*")))
    (is (= (config/javascript-files)
           (string/split config/default-javascript-files #"\s*,\s*")))))
